#+TITLE: Usage
How to use this thing.

This is a specially managed weewiki and zet. Careful usage
is required.

Writing stuff down as I go.

Utilities are stored in the "u" folder. These
are small shell scripts wrapped around weewiki that
do specific things.

Most of what happens here is making logs. Do this
with =u/zsay=.

It is *very* important that you tie whatever is being
said to *exactly one* group that gets explicitely
exported. If you don't, the message will get erased. If
you link more than one, it will get duplicated in the repo.

For general messages, use the =logs= tag.

#+BEGIN_SRC sh
u/zsay @logs
#+END_SRC

Logs are also tied to specific sqlar groups.

Be sure to periodically dump the zet with =dumpzet.sh=.

If you don't do this, stuff won't be saved.

Importing new samples.

First you need to convert the sample collection into a sqlar
archive. Place them into a top level folder and run this
command:

#+BEGIN_SRC sh
sqlar foo.sqlar foo
#+END_SRC

It's *very* important that there isn't a slash after the
foo. For some reason using =foo/= would make it so the
folder doesn't show up in =sqlarfs=.

After this is created it can be imported. Do this from
the directory where the sqlar archive is located, not where
the smp db is located. Then run:

#+BEGIN_SRC sh
weewiki crate import PATH_TO_SMP foo.sqlar
#+END_SRC

See if the import worked with:

#+BEGIN_SRC sh
u/cgroups foo.sqlar
#+END_SRC

Once imported, it's really important to make a new directory
in the smp folder, and optionally a landing page.

From there, it needs to be exported to a TSV file, so
it can be managed in source control.

#+BEGIN_SRC sh
weewiki zet export foo.sqlar foo/zet.tsv
#+END_SRC

Add all these files and make a commit.

After that, you'll need to add these entries to the
=dump_zet.sh= and =mkdb.sh= scripts.

in =dump_zet.sh=, add:

#+BEGIN_SRC sh
zetout foo
#+END_SRC

in =mkdb.sh=, add:

#+BEGIN_SRC sh
zetit foo
#+END_SRC

Finally, don't forget to import any wiki pages in the
=genwiki.janet= script.
